### PR TITLE
Remove broken DAF link

### LINKED ISSUE #42: Link to DAF is broken
The link to https://dataportal.daf.teamdigitale.it in the footer is broken.

### PR DESCRIPTION
**Pull request by sebbalex**
This aims to remove the broken DAF link in footer page.

Fixes #42

### CODE REVIEW

**Review by libremente — COMMENTED** [review]
I don't particularly love this solution... can't we just remove the whole h4?

**Comment by sebbalex** [comment]
> I don't particularly love this solution... can't we just remove the whole h4?

I couldn't be happier :)

**Comment by sebbalex** [comment]
I'm not particularly convinced about the entire footer bar with only an image as placeholder.

I'd consider the idea to remove the entire footer, wdyt?

image

**Comment by libremente** [comment]
+1 on removing the footer (if it's not a painful operation)

**Review by libremente — COMMENTED** [review]
Probably it's also necessary to remove https://github.com/teamdigitale/anpr-dashboard/blob/3623d9998c05386ab5faf0703692464321989678/css/customStyle.css#L221-L230?

**Comment by sebbalex** [comment]
> Probably it's also necessary to remove
> 
> https://github.com/teamdigitale/anpr-dashboard/blob/3623d9998c05386ab5faf0703692464321989678/css/customStyle.css#L221-L230
> 
> ?

good catch

**Review by libremente — APPROVED** [review]

**Pull request merged**
